### ISSUE TITLE
Failed with spaces in the path

### ISSUE THREAD

**Issue by eignatik** [eignatik/LoadTestApp#12]
It looks like as 
> java.lang.IllegalArgumentException: Illegal character in path at index

it happens because we don't use URLEncoder. Space shall to replace with %20 sequence. 

Maybe need to use the following code:
`thePath = URLEncoder.encode(thePath, "UTF-8"); `

or **replaceAll(" ", "%20")** when URL construct I guess

**Comment by lightway82** [comment]
Конечно урл стоит кодировать. Иначе русские символы и пробелы могут стать неожиданностью
А при получении ссылки декодировать ее
