### ISSUE TITLE
Links that looks like a maps.google.com and so on

### ISSUE THREAD

**Issue by eignatik** [eignatik/LoadTestApp#19]
I can't normally get links like maps.google.com. I need to fix removeing protocols and so on and save noramlly URL

**Comment by lightway82** [comment]
Вообще нужно провести эксперименты и сделать так чтобы можно было читать любые uRL
ТАкже важно получать тип ответа от сервера. это может быть ошибка или редирект, нужно уметь ходить по редиректам, тк иногда страницы редиректятся. Например google.ru там редирект стоит.Те записывать в лог возникшие ошибки - типы ответов от сервера и сколько раз они возникли при запросе указанной страницы. И усовершенствовать работу со ссылками с учетом возможных ответов сервера. Если сервер вернул 404 или еще 505 или еще чего-то, то можно сделать запись об ошибке в страницу и пометить ее не выбираемой далее, чтобы исключить ее из списка выбираемых. ТАким образом, Page должен иметь флаг- можно ли его использовать или он уже не рабочий. Это позволит не тратить ресурсы на ошибочные страницы(при случайной выборке эти url игнорить. Также не забыть, что в PAge все ссылки могут оказаться не рабочими, нужно уметь отслеживать этот момент, чтобы выйти из ситупации
